sudo: false
language: c
os:
  - osx
  - linux
compiler:
  - clang
  - gcc
addons:
  apt:
    packages:
      - gfortran
matrix:
  allow_failures:
    - env: MPI_IMPL=openmpi
env:
  - MPI_IMPL=mpich
    PORT=mpi-ts
  - MPI_IMPL=mpich
    PORT=mpi-mt
  - MPI_IMPL=mpich
    PORT=mpi-pt
  - MPI_IMPL=mpich
    PORT=mpi-pr
  - MPI_IMPL=mpich
    PORT=mpi3
  - MPI_IMPL=openmpi
    PORT=mpi-ts
  - MPI_IMPL=mpich
    PORT=mpi-ts
    CONFIG_OPTS="--disable-f77 --enable-cxx"
  - MPI_IMPL=mpich
    PORT=mpi-ts
    CONFIG_OPTS="--disable-static --enable-shared"
  - MPI_IMPL=mpich
    PORT=ofi
before_install:
  - export TRAVIS_ROOT=$HOME/travis
  - mkdir $TRAVIS_ROOT
  - sh ./travis/install-autotools.sh $TRAVIS_ROOT
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc || brew upgrade gcc || true; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install coreutils || brew upgrade coreutils || true; fi
  - sh ./travis/install-mpi.sh $TRAVIS_ROOT $MPI_IMPL
  - if [[ "$PORT" == "ofi" ]]; then sh ./travis/install-libfabric.sh $TRAVIS_ROOT; fi
script:
  - sh ./travis/build-run.sh $TRAVIS_ROOT $PORT $MPI_IMPL
after_failure:
  - cat ./test-suite.log
  - find . -name "*.log" -exec head -n 100 {} ";"
